services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://yourusername:yourpassword@db:5432/yourdbname

volumes:
  postgres_data: