"""del file_data

Revision ID: 761bcc496485
Revises: 1c58a25e810c
Create Date: 2024-12-16 15:32:28.047404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '761bcc496485'
down_revision: Union[str, None] = '1c58a25e810c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_data', postgresql.BYTEA(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
