"""new generation table

Revision ID: 92f30e6821a1
Revises: 3ce7b63a68b9
Create Date: 2024-12-03 14:55:27.962567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92f30e6821a1'
down_revision: Union[str, None] = '3ce7b63a68b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'logs', 'users', ['user_id'], ['user_id'])
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_constraint(None, 'logs', type_='foreignkey')
    # ### end Alembic commands ###
